import type { FieldSpec } from '../core/interfaces/field-spec';

export const ISO_8583_1987_SPEC: Readonly<Record<number, FieldSpec>> = {
  1: { name: 'Second Bitmap', type: 'fixed', length: 16, format: 'b' },
  2: { name: 'Primary Account Number (PAN)', type: 'llvar', length: 19, format: 'n' },
  3: { name: 'Processing Code', type: 'fixed', length: 6, format: 'n' },
  4: { name: 'Amount, Transaction', type: 'fixed', length: 12, format: 'n' },
  5: { name: 'Amount, Settlement', type: 'fixed', length: 12, format: 'n' },
  6: { name: 'Amount, Cardholder Billing', type: 'fixed', length: 12, format: 'n' },
  7: { name: 'Transmission Date & Time', type: 'fixed', length: 10, format: 'n' },
  8: { name: 'Amount, Cardholder Billing Fee', type: 'fixed', length: 8, format: 'n' },
  9: { name: 'Conversion Rate, Settlement', type: 'fixed', length: 8, format: 'n' },
  10: { name: 'Conversion Rate, Cardholder Billing', type: 'fixed', length: 8, format: 'n' },
  11: { name: 'Systems Trace Audit Number (STAN)', type: 'fixed', length: 6, format: 'n' },
  12: { name: 'Time, Local Transaction', type: 'fixed', length: 6, format: 'n' },
  13: { name: 'Date, Local Transaction', type: 'fixed', length: 4, format: 'n' },
  14: { name: 'Date, Expiration', type: 'fixed', length: 4, format: 'n' },
  15: { name: 'Date, Settlement', type: 'fixed', length: 4, format: 'n' },
  16: { name: 'Date, Conversion', type: 'fixed', length: 4, format: 'n' },
  17: { name: 'Date, Capture', type: 'fixed', length: 4, format: 'n' },
  18: { name: 'Merchant Type', type: 'fixed', length: 4, format: 'n' },
  19: { name: 'Acquiring Institution Country Code', type: 'fixed', length: 3, format: 'n' },
  20: { name: 'PAN Extended, Country Code', type: 'fixed', length: 3, format: 'n' },
  21: { name: 'Forwarding Institution Country Code', type: 'fixed', length: 3, format: 'n' },
  22: { name: 'Point of Service Entry Mode', type: 'fixed', length: 3, format: 'n' },
  23: { name: 'Application PAN Sequence Number', type: 'fixed', length: 3, format: 'n' },
  24: { name: 'Function Code (NII)', type: 'fixed', length: 3, format: 'n' },
  25: { name: 'Point of Service Condition Code', type: 'fixed', length: 2, format: 'n' },
  26: { name: 'Point of Service Capture Code', type: 'fixed', length: 2, format: 'n' },
  27: { name: 'Authorizing Identification Response Length', type: 'fixed', length: 1, format: 'n' },
  28: { name: 'Amount, Transaction Fee', type: 'fixed', length: 9, format: 'xn' },
  29: { name: 'Amount, Settlement Fee', type: 'fixed', length: 9, format: 'xn' },
  30: { name: 'Amount, Transaction Processing Fee', type: 'fixed', length: 9, format: 'xn' },
  31: { name: 'Amount, Settlement Processing Fee', type: 'fixed', length: 9, format: 'xn' },
  32: { name: 'Acquiring Institution Identification Code', type: 'llvar', length: 11, format: 'n' },
  33: { name: 'Forwarding Institution Identification Code', type: 'llvar', length: 11, format: 'n' },
  34: { name: 'Primary Account Number, Extended', type: 'llvar', length: 28, format: 'ns' },
  35: { name: 'Track 2 Data', type: 'llvar', length: 37, format: 'z' },
  36: { name: 'Track 3 Data', type: 'lllvar', length: 104, format: 'z' },
  37: { name: 'Retrieval Reference Number', type: 'fixed', length: 12, format: 'an' },
  38: { name: 'Authorization Identification Response', type: 'fixed', length: 6, format: 'an' },
  39: { name: 'Response Code', type: 'fixed', length: 2, format: 'an' },
  40: { name: 'Service Restriction Code', type: 'fixed', length: 3, format: 'an' },
  41: { name: 'Card Acceptor Terminal Identification', type: 'fixed', length: 8, format: 'ans' },
  42: { name: 'Card Acceptor Identification Code', type: 'fixed', length: 15, format: 'ans' },
  43: { name: 'Card Acceptor Name/Location', type: 'fixed', length: 40, format: 'ans' },
  44: { name: 'Additional Response Data', type: 'llvar', length: 25, format: 'an' },
  45: { name: 'Track 1 Data', type: 'llvar', length: 76, format: 'an' },
  46: { name: 'Additional Data - ISO', type: 'lllvar', length: 999, format: 'ans' },
  47: { name: 'Additional Data - National', type: 'lllvar', length: 999, format: 'ans' },
  48: { name: 'Additional Data - Private', type: 'lllvar', length: 999, format: 'ans' },
  49: { name: 'Currency Code, Transaction', type: 'fixed', length: 3, format: 'an' },
  50: { name: 'Currency Code, Settlement', type: 'fixed', length: 3, format: 'an' },
  51: { name: 'Currency Code, Cardholder Billing', type: 'fixed', length: 3, format: 'an' },
  52: { name: 'Personal Identification Number (PIN) Data', type: 'fixed', length: 16, format: 'b' },
  53: { name: 'Security Related Control Information', type: 'fixed', length: 16, format: 'n' },
  54: { name: 'Additional Amounts', type: 'lllvar', length: 120, format: 'an' },
  55: { name: 'ICC Data - EMV', type: 'lllvar', length: 999, format: 'ans' },
  56: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  57: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  58: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  59: { name: 'Referrals', type: 'lllvar', length: 999, format: 'ans' },
  60: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  61: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  62: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  63: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  64: { name: 'Message Authentication Code (MAC)', type: 'fixed', length: 8, format: 'b' },
  65: { name: 'Secondary Bitmap', type: 'fixed', length: 16, format: 'b' },
  66: { name: 'Settlement Code', type: 'fixed', length: 1, format: 'n' },
  67: { name: 'Extended Payment Code', type: 'fixed', length: 2, format: 'n' },
  68: { name: 'Receiving Institution Country Code', type: 'fixed', length: 3, format: 'n' },
  69: { name: 'Settlement Institution Country Code', type: 'fixed', length: 3, format: 'n' },
  70: { name: 'Network Management Information Code', type: 'fixed', length: 3, format: 'n' },
  71: { name: 'Message Number', type: 'fixed', length: 8, format: 'n' },
  72: { name: 'Data Record', type: 'lllvar', length: 999, format: 'ans' },
  73: { name: 'Action Date', type: 'fixed', length: 6, format: 'n' },
  74: { name: 'Credits, Number', type: 'fixed', length: 10, format: 'n' },
  75: { name: 'Credits, Reversal Number', type: 'fixed', length: 10, format: 'n' },
  76: { name: 'Debits, Number', type: 'fixed', length: 10, format: 'n' },
  77: { name: 'Debits, Reversal Number', type: 'fixed', length: 10, format: 'n' },
  78: { name: 'Transfer, Number', type: 'fixed', length: 10, format: 'n' },
  79: { name: 'Transfer, Reversal Number', type: 'fixed', length: 10, format: 'n' },
  80: { name: 'Inquiries, Number', type: 'fixed', length: 10, format: 'n' },
  81: { name: 'Authorizations, Number', type: 'fixed', length: 10, format: 'n' },
  82: { name: 'Credits, Processing Fee Amount', type: 'fixed', length: 12, format: 'n' },
  83: { name: 'Credits, Transaction Fee Amount', type: 'fixed', length: 12, format: 'n' },
  84: { name: 'Debits, Processing Fee Amount', type: 'fixed', length: 12, format: 'n' },
  85: { name: 'Debits, Transaction Fee Amount', type: 'fixed', length: 12, format: 'n' },
  86: { name: 'Credits, Amount', type: 'fixed', length: 16, format: 'n' },
  87: { name: 'Credits, Reversal Amount', type: 'fixed', length: 16, format: 'n' },
  88: { name: 'Debits, Amount', type: 'fixed', length: 16, format: 'n' },
  89: { name: 'Debits, Reversal Amount', type: 'fixed', length: 16, format: 'n' },
  90: { name: 'Original Data Elements', type: 'fixed', length: 42, format: 'n' },
  91: { name: 'File Update Code', type: 'fixed', length: 1, format: 'an' },
  92: { name: 'File Security Code', type: 'fixed', length: 2, format: 'an' },
  93: { name: 'Response Indicator', type: 'fixed', length: 5, format: 'an' },
  94: { name: 'Service Indicator', type: 'fixed', length: 7, format: 'an' },
  95: { name: 'Replacement Amounts', type: 'fixed', length: 42, format: 'an' },
  96: { name: 'Message Security Code', type: 'fixed', length: 16, format: 'b' },
  97: { name: 'Amount, Net Settlement', type: 'fixed', length: 17, format: 'xn' },
  98: { name: 'Payee', type: 'fixed', length: 25, format: 'ans' },
  99: { name: 'Settlement Institution ID Code', type: 'llvar', length: 11, format: 'n' },
  100: { name: 'Receiving Institution ID Code', type: 'llvar', length: 11, format: 'n' },
  101: { name: 'File Name', type: 'llvar', length: 17, format: 'ans' },
  102: { name: 'Account Identification 1', type: 'llvar', length: 28, format: 'ans' },
  103: { name: 'Account Identification 2', type: 'llvar', length: 28, format: 'ans' },
  104: { name: 'Transaction Description', type: 'lllvar', length: 100, format: 'ans' },
  105: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  106: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  107: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  108: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  109: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  110: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  111: { name: 'Reserved ISO', type: 'lllvar', length: 999, format: 'ans' },
  112: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  113: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  114: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  115: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  116: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  117: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  118: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  119: { name: 'Reserved National', type: 'lllvar', length: 999, format: 'ans' },
  120: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  121: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  122: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  123: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  124: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  125: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  126: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  127: { name: 'Reserved Private', type: 'lllvar', length: 999, format: 'ans' },
  128: { name: 'Message Authentication Code (MAC)', type: 'fixed', length: 8, format: 'b' },
};
