export const fieldDescriptions: Record<number, string> = {
  1: 'Second Bitmap',
  2: 'Primary Account Number (PAN)',
  3: 'Processing Code',
  4: 'Amount, Transaction',
  5: 'Amount, Settlement',
  6: 'Amount, Cardholder Billing',
  7: 'Transmission Date & Time',
  8: 'Amount, Cardholder Billing Fee',
  9: 'Conversion Rate, Settlement',
  10: 'Conversion Rate, Cardholder Billing',
  11: 'Systems Trace Audit Number (STAN)',
  12: 'Time, Local Transaction',
  13: 'Date, Local Transaction',
  14: 'Date, Expiration',
  15: 'Date, Settlement',
  16: 'Date, Conversion',
  17: 'Date, Capture',
  18: 'Merchant Type (MCC)',
  19: 'Acquiring Institution Country Code',
  20: 'PAN Extended, Country Code',
  21: 'Forwarding Institution Country Code',
  22: 'Point of Service Entry Mode',
  23: 'Application PAN Sequence Number',
  24: 'Function Code (NII)',
  25: 'Point of Service Condition Code',
  26: 'Point of Service Capture Code',
  27: 'Authorizing Identification Response Length',
  28: 'Amount, Transaction Fee',
  29: 'Amount, Settlement Fee',
  30: 'Amount, Transaction Processing Fee',
  31: 'Amount, Settlement Processing Fee',
  32: 'Acquiring Institution Identification Code',
  33: 'Forwarding Institution Identification Code',
  34: 'Primary Account Number, Extended',
  35: 'Track 2 Data',
  36: 'Track 3 Data',
  37: 'Retrieval Reference Number',
  38: 'Authorization Identification Response',
  39: 'Response Code',
  40: 'Service Restriction Code',
  41: 'Card Acceptor Terminal Identification',
  42: 'Card Acceptor Identification Code',
  43: 'Card Acceptor Name/Location',
  44: 'Additional Response Data',
  45: 'Track 1 Data',
  46: 'Additional Data - ISO',
  47: 'Additional Data - National',
  48: 'Additional Data - Private',
  49: 'Currency Code, Transaction',
  50: 'Currency Code, Settlement',
  51: 'Currency Code, Cardholder Billing',
  52: 'Personal Identification Number (PIN) Data',
  53: 'Security Related Control Information',
  54: 'Additional Amounts',
  55: 'ICC Data - EMV',
  56: 'Reserved ISO',
  57: 'Reserved National',
  58: 'Reserved Private',
  59: 'Referrals',
  60: 'Reserved Private',
  61: 'Reserved Private',
  62: 'Reserved Private',
  63: 'Reserved Private',
  64: 'Message Authentication Code (MAC)',
  65: 'Secondary Bitmap',
  66: 'Settlement Code',
  67: 'Extended Payment Code',
  68: 'Receiving Institution Country Code',
  69: 'Settlement Institution Country Code',
  70: 'Network Management Information Code',
  71: 'Message Number',
  72: 'Data Record',
  73: 'Action Date',
  74: 'Credits, Number',
  75: 'Credits, Reversal Number',
  76: 'Debits, Number',
  77: 'Debits, Reversal Number',
  78: 'Transfer, Number',
  79: 'Transfer, Reversal Number',
  80: 'Inquiries, Number',
  81: 'Authorizations, Number',
  82: 'Credits, Processing Fee Amount',
  83: 'Credits, Transaction Fee Amount',
  84: 'Debits, Processing Fee Amount',
  85: 'Debits, Transaction Fee Amount',
  86: 'Credits, Amount',
  87: 'Credits, Reversal Amount',
  88: 'Debits, Amount',
  89: 'Debits, Reversal Amount',
  90: 'Original Data Elements',
  91: 'File Update Code',
  92: 'File Security Code',
  93: 'Response Indicator',
  94: 'Service Indicator',
  95: 'Replacement Amounts',
  96: 'Message Security Code',
  97: 'Amount, Net Settlement',
  98: 'Payee',
  99: 'Settlement Institution ID Code',
  100: 'Receiving Institution ID Code',
  101: 'File Name',
  102: 'Account Identification 1',
  103: 'Account Identification 2',
  104: 'Transaction Description',
  105: 'Reserved ISO',
  106: 'Reserved ISO',
  107: 'Reserved ISO',
  108: 'Reserved ISO',
  109: 'Reserved ISO',
  110: 'Reserved ISO',
  111: 'Reserved ISO',
  112: 'Reserved National',
  113: 'Reserved National',
  114: 'Reserved National',
  115: 'Reserved National',
  116: 'Reserved National',
  117: 'Reserved National',
  118: 'Reserved National',
  119: 'Reserved National',
  120: 'Reserved Private',
  121: 'Reserved Private',
  122: 'Reserved Private',
  123: 'Reserved Private',
  124: 'Reserved Private',
  125: 'Reserved Private',
  126: 'Reserved Private',
  127: 'Reserved Private',
  128: 'Message Authentication Code (MAC)',
};
